# Generated by Django 4.2.7 on 2025-11-30 10:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('company_type', models.CharField(choices=[('PRODUCT', 'Product Based'), ('SERVICE', 'Service Based'), ('STARTUP', 'Startup'), ('MNC', 'Multinational Corporation')], max_length=20)),
                ('website', models.URLField(blank=True)),
                ('package_offered', models.DecimalField(decimal_places=2, help_text='Package in LPA', max_digits=10)),
                ('min_cgpa_required', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('eligible_branches', models.CharField(help_text='Comma-separated branch codes', max_length=200)),
                ('job_role', models.CharField(max_length=200)),
                ('job_location', models.CharField(max_length=200)),
                ('contact_person', models.CharField(max_length=200)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['-package_offered'],
            },
        ),
        migrations.CreateModel(
            name='PlacementStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('stage_type', models.CharField(choices=[('APPLICATION', 'Application Submission'), ('APTITUDE', 'Aptitude Test'), ('TECHNICAL1', 'Technical Round 1'), ('TECHNICAL2', 'Technical Round 2'), ('TECHNICAL3', 'Technical Round 3'), ('HR', 'HR Round'), ('FINAL', 'Final Selection')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('sequence_order', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['sequence_order'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_number', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('branch', models.CharField(choices=[('CSE', 'Computer Science and Engineering'), ('IT', 'Information Technology'), ('ECE', 'Electronics and Communication Engineering'), ('ME', 'Mechanical Engineering'), ('CE', 'Civil Engineering'), ('EE', 'Electrical Engineering')], max_length=10)),
                ('year', models.CharField(choices=[('1', 'First Year'), ('2', 'Second Year'), ('3', 'Third Year'), ('4', 'Fourth Year')], max_length=1)),
                ('cgpa', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('skills', models.TextField(help_text='Comma-separated skills')),
                ('is_placed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlacementProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('APPLIED', 'Applied'), ('IN_PROGRESS', 'In Progress'), ('SHORTLISTED', 'Shortlisted'), ('SELECTED', 'Selected'), ('REJECTED', 'Rejected'), ('OFFER_RECEIVED', 'Offer Received'), ('OFFER_ACCEPTED', 'Offer Accepted'), ('OFFER_DECLINED', 'Offer Declined')], default='APPLIED', max_length=20)),
                ('application_date', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='placements.company')),
                ('current_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_students', to='placements.placementstage')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='placements.student')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('student', 'company')},
            },
        ),
        migrations.CreateModel(
            name='ImportantDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('event_type', models.CharField(choices=[('DRIVE', 'Placement Drive'), ('DEADLINE', 'Application Deadline'), ('TEST', 'Test/Assessment'), ('INTERVIEW', 'Interview'), ('RESULT', 'Result Announcement'), ('OTHER', 'Other')], max_length=20)),
                ('event_date', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='important_dates', to='placements.company')),
            ],
            options={
                'ordering': ['event_date'],
            },
        ),
        migrations.CreateModel(
            name='StageProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('PENDING', 'Pending'), ('CLEARED', 'Cleared'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('scheduled_date', models.DateTimeField(blank=True, null=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('placement_progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_details', to='placements.placementprogress')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placements.placementstage')),
            ],
            options={
                'ordering': ['stage__sequence_order'],
                'unique_together': {('placement_progress', 'stage')},
            },
        ),
    ]
