# Generated by Django 4.2.7 on 2025-11-30 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importantdate',
            name='link',
            field=models.URLField(blank=True, help_text='Event registration or meeting link', max_length=500),
        ),
    ]
